ALTER TABLE public.tournaments
ADD COLUMN IF NOT EXISTS prize_first INTEGER NOT NULL DEFAULT 100,
ADD COLUMN IF NOT EXISTS prize_second INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS prize_third INTEGER NOT NULL DEFAULT 0;
